### ISSUE TITLE
Lavalink v4 Issues

### ISSUE THREAD

**Issue by ItzZoldy** [shittybot/lavalink-status#20]
1. It only shows 1 Lavalink server's information even if I set 2-3 nodes on config.js.
2. Lavalink load information doesn't work.

**Comment by LewdHuTao** [comment]
Must be an issue with the wrapper i made. Unfortunately i cant fix it right now, you have to wait for a few weeks for this issue to fix. I'll keep this issue open until it's really fix, thank you for reporting this issue

**Comment by ZoldZap** [comment]
@LewdHuTao Take your time and Welcome :)

**Comment by ZoldZap** [comment]
@LewdHuTao I am not sure but I guess v3 can be same issues.

**Comment by LewdHuTao** [comment]
V3 should work fine i never touched the code for a long time. Unless erela.js wrapper is completely unusable. I will test both code in a few weeks and will let you know.

**Comment by LewdHuTao** [comment]
![image](https://github.com/shittybot/lavalink-status/assets/90232327/81443db6-7a01-4f2a-9a8a-7990dd43d846)

node should now map properly in v4 version. sorry for taking a long time to fix this issue

**Comment by LewdHuTao** [comment]
> @LewdHuTao I am not sure but I guess v3 can be same issues.

I tested it out and it work perfectly fine, make sure you configure them correctly. I'll close this, feel free to open it again if there is a new issue.
